# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.mock.data.generator:
        class: AppBundle\Service\DataGenerator

    app.form.data.logger:
        class: AppBundle\Service\PostLogger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: form }

    app.form.data.logger.formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: [null, null, true, true]

